dist: trusty
sudo: required
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    env:
    - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
install:
- sudo apt-get -y install g++-6-multilib nasm make xorriso mtools grub-pc grub-common
language: cpp
compiler:
- g++
script:
- make iso
- file build/hanaos.iso

deploy:
  provider: releases
  api_key:
    secure: f05GEek92Cv5Ohu7+JC2HlG2izk6QJuHABBNctmOrB1dqMrgBAnK9QG1MWzE5/ZcLaNUkU/VB2Rod86I7Y7xMhu0J6LbFFw/4r8dJN+eVxhVqnbGZp0Wrn9gS8yPxt1nyhcFRyYSDqJms/iMT/GRDctQQE+dOx9AoK3ESaODVE2jhZNvLbi2ahS2z56R73exCIJbPIR/KSp/3bHeS4DH3ZZ8/aH6H312JmM69u0ZLvInEuEofbzUaZr2O8OTCpOnhhTbfWPA1L8vnpfMHOgJmtVvwVW67CqK2kR0afe7DLACbj+mdxEXewrVdUYsmAfKFFl+gZzfWlcQ34g59QIrSt1pzDkCAyP8aJ6uBb8Y1ceVBlqhiciRmCBZg7oHXa422LCH8GvD+lptcQ5/DLkpjeA7BCvauqPc9nwQxYQK4Qy1PyLVIqvvXepHUL8HA3TqqaG7qn/5J+kD2YWSjBhURuvw2IN442SmvLeYlXMxzTgezaHRxvcoTWf28IMD2YJ7Bx2+iiHudUPY3yhVAWrRpCTkYwRjslpll6msH6w/0LqukKSSEw6mbjGml7Q3PZ/v5gsYsVv1bJZHHryWpMVM2iNT/72Dv8Gsf6TFQ9I16Y53INXd/36vawgArAt/FsGZhPjbQAkLzQTw2Vv0+vmynC5TcDCdHW82lpiTh44JFoY=
  file: build/hanaos.iso
  skip_cleanup: true
  on:
    repo: imxieyi/HanaOS
